In [ ]:
#csv파일 읽어오기
#pandas.read_csv("파일경로")

import pandas as pd
import os 

#os.listdir("./")
os.listdir("./data") #지금뭐있는지보여줘
file_path = "./data/read_csv_sample.csv"
print(file_path)

file_path2=os.path.join("data","read_csv_sample.csv")
print(file_path2)

In [ ]:
import pandas as pd
import os 

df1= pd.read_csv("./data/read_csv_sample.csv")
df1
df2= pd.read_csv("./data/read_csv_sample.csv",header=None)
#아무것도 안적었을땐 첫번째행이 헤더로 들어옴
df2

In [ ]:
df3=pd.read_csv("./data/read_csv_sample.csv",index_col=None)
df3

In [ ]:
df4=pd.read_csv("./data/read_csv_sample.csv",index_col="c0")
df4

In [ ]:
#엑셀파일읽어오기
import pandas as pd
import os 

df=pd.read_excel("./data/남북한발전전력량.xlsx",engine="openpyxl")
df

In [8]:
#엑셀파일읽어오기
import pandas as pd
import os 

df2=pd.read_excel("./data/남북한발전전력량.xlsx",engine="openpyxl",header=None)
df2.head(5)

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,28
0,전력량 (억㎾h),발전 전력별,1990,1991,1992,1993,1994,1995,1996,1997,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
1,남한,합계,1077,1186,1310,1444,1650,1847,2055,2244,...,4031,4224,4336,4747,4969,5096,5171,5220,5281,5404
2,NaN,수력,64,51,49,60,41,55,52,54,...,50,56,56,65,78,77,84,78,58,66
3,NaN,화력,484,573,696,803,1022,1122,1264,1420,...,2551,2658,2802,3196,3343,3430,3581,3427,3402,3523
4,NaN,원자력,529,563,565,581,587,670,739,771,...,1429,1510,1478,1486,1547,1503,1388,1564,1648,1620

In [13]:
#Json파일 불러오기 
import pandas as pd
df=pd.read_json("./data/read_json_sample.json")
print(df)
df2 = pd.read_json("./data/read_json_sample.json",orient="index")
df2

            year        developer opensource
pandas      2008    Wes Mckinneye       True
NumPy       2006  Travis Oliphant       True
matplotlib  2003   John D. Hunter       True

                   pandas            NumPy      matplotlib
year                 2008             2006            2003
developer   Wes Mckinneye  Travis Oliphant  John D. Hunter
opensource           True             True            True

In [12]:
df3 = pd.read_json("./data/read_json_sample.json",orient="columns")
df3

            year        developer opensource
pandas      2008    Wes Mckinneye       True
NumPy       2006  Travis Oliphant       True
matplotlib  2003   John D. Hunter       True