In [55]:
#시리즈원소에 함수 매핑
#series객체.apply(매핑함수)

import seaborn as sns
import pandas as pd

titanic=sns.load_dataset("titanic")
df=titanic.loc[:, ["age","fare"]]
df.head()
df=titanic.loc[0:8, :]
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False

In [2]:
def add_10(n):
    return n+10

def add_two_abj(a,b):
    return a+b

In [5]:
print(add_10(10))
print(add_two_abj(10,10))

20
20

In [9]:
df["age"].head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [10]:
sr1=df["age"].apply(add_10)
#함수안에 함수를 호출할때는 바로실행하는게아니고 마지막에 실행되길원하기때문에 add_10 만해줌 add_10() X
sr1.head()

0    32.0
1    48.0
2    36.0
3    45.0
4    45.0
Name: age, dtype: float64

In [11]:
#람다함수 
sr2=df["age"].apply(lambda n : n+10)
sr2.head()

0    32.0
1    48.0
2    36.0
3    45.0
4    45.0
Name: age, dtype: float64

In [13]:
imsi = lambda n : n+10
imsi(df["age"])

0      32.0
1      48.0
2      36.0
3      45.0
4      45.0
       ...
886    37.0
887    29.0
888     NaN
889    36.0
890    42.0
Name: age, Length: 891, dtype: float64

In [15]:
sr4= df["age"].apply(add_two_abj,b=10)
sr4.head()

0    32.0
1    48.0
2    36.0
3    45.0
4    45.0
Name: age, dtype: float64

In [16]:
sr5=df["age"].apply(lambda a,b : a+b ,b=10)
sr5

0      32.0
1      48.0
2      36.0
3      45.0
4      45.0
       ...
886    37.0
887    29.0
888     NaN
889    36.0
890    42.0
Name: age, Length: 891, dtype: float64

In [23]:
#시리즈객체 함수매핑
#데이터프레임 각열에 함수매핑
def calculae_state(col):
    max_val= col.max()
    min_val = col.min()
    mean_val= col.mean()
    median_val = col.median()
    return pd.Series(
        [max_val,min_val,mean_val,median_val],
        index=["Max","Min","Mean","Median"]
    )

result_df=df.apply(calculae_state,axis=0)
result_df

              age        fare
Max     80.000000  512.329200
Min      0.420000    0.000000
Mean    29.699118   32.204208
Median  28.000000   14.454200

In [24]:
result_sr=df.apply(lambda x:x.max()-x.min())
result_sr

age      79.5800
fare    512.3292
dtype: float64

In [28]:
def calculate_diff_avg(row):
    diff = row.max() - row.min()
    avg = row.mean()

    return pd.Series([diff,avg],index=["차이","평균"])

result_df2=df.apply(calculate_diff_avg,axis=1)
result_df2

          차이        평균
0    14.7500  14.62500
1    33.2833  54.64165
2    18.0750  16.96250
3    18.1000  44.05000
4    26.9500  21.52500
..       ...       ...
886  14.0000  20.00000
887  11.0000  24.50000
888   0.0000  23.45000
889   4.0000  28.00000
890  24.2500  19.87500

[891 rows x 2 columns]

In [33]:
titanic.head()
df1=titanic.loc[:,["age","fare"]] #콤마를기준으로 행 :는 모든 행을다가져오겠다
df2=titanic.loc[:,["embark_town","embarked"]] #콤마를기준으로 행 :는 모든 행을다가져오겠다
def missing_value(df):
    return df.isnull()

result_df=df1.pipe(missing_value)
result_df

       age   fare
0    False  False
1    False  False
2    False  False
3    False  False
4    False  False
..     ...    ...
886  False  False
887  False  False
888   True  False
889  False  False
890  False  False

[891 rows x 2 columns]

In [37]:
def missing_count(df):
    return missing_value(df).sum()
result_series=df1.pipe(missing_count)
result_series

age     177
fare      0
dtype: int64

In [38]:
df1.isnull().sum()

age     177
fare      0
dtype: int64

In [48]:
def extract_initial(df):
    df["town_initial"] = df["embark_town"].str[0]
    return df 
def verify_initial(df):
    df["veridfied"]=df["embarked"] == df["town_initial"]
    return df
df2.head()
imsi=verify_initial(extract_initial(df2))
verify_initial(imsi)

     embark_town embarked town_initial  veridfied
0    Southampton        S            S       True
1      Cherbourg        C            C       True
2    Southampton        S            S       True
3    Southampton        S            S       True
4    Southampton        S            S       True
..           ...      ...          ...        ...
886  Southampton        S            S       True
887  Southampton        S            S       True
888  Southampton        S            S       True
889    Cherbourg        C            C       True
890   Queenstown        Q            Q       True

[891 rows x 4 columns]

In [51]:
titanic.head()
df1=titanic.loc[:,["age","fare"]] #콤마를기준으로 행 :는 모든 행을다가져오겠다
df2=titanic.loc[:,["embark_town","embarked"]] #콤마를기준으로 행 :는 모든 행을다가져오겠다
df2.pipe(extract_initial).pipe(verify_initial)

     embark_town embarked town_initial  veridfied
0    Southampton        S            S       True
1      Cherbourg        C            C       True
2    Southampton        S            S       True
3    Southampton        S            S       True
4    Southampton        S            S       True
..           ...      ...          ...        ...
886  Southampton        S            S       True
887  Southampton        S            S       True
888  Southampton        S            S       True
889    Cherbourg        C            C       True
890   Queenstown        Q            Q       True

[891 rows x 4 columns]