In [ ]:
#2가지이상의 시리즈를 가지고있을때 데이터프레임
import pandas as pd

In [ ]:
#데이터프레임 = pandas.DataFrame(데이터)
#시리즈 =pandas.Series(데이터)

In [2]:
import pandas as pd

dict_data={
    "c0":[1,2,3],
    "c1":[4,5,6],
    "c2":[7,8,9],
    "c3":[10,11,12],
    "c4":[13,14,15]
}

df = pd.DataFrame(dict_data)
print(type(df))
print(df)

<class 'pandas.DataFrame'>
   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [8]:
#행 인덱스 /열 이름 설정
import pandas as pd
data=[
    [15,"남","덕영중"],
    [17,"여","수리중"]
]

df=pd.DataFrame(data, index=["준서","예은"],columns=["나이","성별","학교"])
print(df)
print(df.index)
print(df.columns)
#2행3열

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중
Index(['준서', '예은'], dtype='str')
Index(['나이', '성별', '학교'], dtype='str')

In [13]:
df.index = ["학생1","학생2"]
df

     나이 성별   학교
학생1  15  남  덕영중
학생2  17  여  수리중

In [14]:
df.columns =["연령","남녀","소속"]
df

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [19]:
import pandas as pd
data=[
    [15,"남","덕영중"],
    [17,"여","수리중"]
]
df=pd.DataFrame(data, index=["준서","예은"],columns=["나이","성별","학교"])
df= df.rename(columns={"나이":"연령","성별":"남녀","학교":"소속"})
df

    연령 남녀   소속
준서  15  남  덕영중
예은  17  여  수리중

In [22]:
df=df.rename(index={
    "준서":"학생1",
    "예은":"학생2"
})
df

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [24]:
# #행/열 삭제
# 행삭제:DataFrame객체.drop(행인덱스 또는 배열,axis=0또는 axis="index") #기본은 0
# 열삭제:DataFrame객체.drop(열이름 똔느 배열 , axis=1 또는 axis="colums") 
# 지울때 엑시스로 지우려면 가로가0 집계함수할때는 세로가 0 
#헷갈리니까 엑시스 index와 colums쓰자

In [ ]:
# 행삭제:DataFrame객체.drop(행인덱스 또는 배열,axis=0또는 axis="index") #기본은 0
# 열삭제:DataFrame객체.drop(열이름 똔느 배열 , axis=1 또는 axis="colums") 
import pandas as pd

exam_data = {
    "수학":[90,80,70],
    "영어":[98,89,95],
    "음악":[85,95,100],
    "체육":[100,90,90]
}
pd.DataFrame(exam_data,index=["서준","우현","인한"])

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인한  70  95  100   90

In [32]:
import pandas as pd

exam_data = {
    "수학":[90,80,70],
    "영어":[98,89,95],
    "음악":[85,95,100],
    "체육":[100,90,90]
}
df=pd.DataFrame(exam_data,index=["서준","우현","인한"])

df2 = df.copy()
df2= df2.drop("우현",axis=0) #axis=0 기본값이라 안써도 자동으로 우현지워짐
df2

    수학  영어   음악   체육
서준  90  98   85  100
인한  70  95  100   90

In [35]:
import pandas as pd

exam_data = {
    "수학":[90,80,70],
    "영어":[98,89,95],
    "음악":[85,95,100],
    "체육":[100,90,90]
}
df=pd.DataFrame(exam_data,index=["서준","우현","인한"])

df3 = df.copy()
df3 = df3.drop(["우현","인한"],axis=0)
df3

    수학  영어  음악   체육
서준  90  98  85  100

In [36]:
df5 = df.copy()
df5.drop(index=["우현"])

    수학  영어   음악   체육
서준  90  98   85  100
인한  70  95  100   90

In [39]:
#열삭제
df2=df.copy()
df2.drop("수학",axis=1)

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인한  95  100   90

In [40]:
df3=df.copy()
df3 = df3.drop(["영어","음악"],axis=1)
df3

    수학   체육
서준  90  100
우현  80   90
인한  70   90

In [46]:
df4 = df.copy()
df4= df4.drop(["영어","음악"],axis="columns")
df4

    수학   체육
서준  90  100
우현  80   90
인한  70   90

In [48]:
df5 = df.copy()
df5= df5.drop(columns=["수학"])
df5

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인한  95  100   90