In [45]:
# 그룹 객체 만들기
# DataFrame객체.groupby(기준이 되는 열)

import pandas as pd
import seaborn as sns

titanic = sns.load_dataset("titanic")
df = titanic.loc[:, ["age", "sex", "class", "fare", "survived"]]
df.head()

    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
1  38.0  female  First  71.2833         1
2  26.0  female  Third   7.9250         1
3  35.0  female  First  53.1000         1
4  35.0    male  Third   8.0500         0

In [46]:
df["class"].unique()

['Third', 'First', 'Second']
Categories (3, str): ['First', 'Second', 'Third']

In [47]:
df["class"].value_counts()

class
Third     491
First     216
Second    184
Name: count, dtype: int64

In [48]:
df["class"].nunique()

3

In [49]:
grouped = df.groupby(["class"], observed=True)
grouped

In [50]:
for key, group in grouped:
    print(key)
    print(group.head())
    print()

('First',)
     age     sex  class     fare  survived
1   38.0  female  First  71.2833         1
3   35.0  female  First  53.1000         1
6   54.0    male  First  51.8625         0
11  58.0  female  First  26.5500         1
23  28.0    male  First  35.5000         1

('Second',)
     age     sex   class     fare  survived
9   14.0  female  Second  30.0708         1
15  55.0  female  Second  16.0000         1
17   NaN    male  Second  13.0000         1
20  35.0    male  Second  26.0000         0
21  34.0    male  Second  13.0000         1

('Third',)
    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
2  26.0  female  Third   7.9250         1
4  35.0    male  Third   8.0500         0
5   NaN    male  Third   8.4583         0
7   2.0    male  Third  21.0750         0

In [51]:
average = grouped.mean(numeric_only=True)
average

              age       fare  survived
class
First   38.233441  84.154687  0.629630
Second  29.877630  20.662183  0.472826
Third   25.140620  13.675550  0.242363

In [52]:
group3 = grouped.get_group(("Third",))
group3

      age     sex  class     fare  survived
0    22.0    male  Third   7.2500         0
2    26.0  female  Third   7.9250         1
4    35.0    male  Third   8.0500         0
5     NaN    male  Third   8.4583         0
7     2.0    male  Third  21.0750         0
..    ...     ...    ...      ...       ...
882  22.0  female  Third  10.5167         0
884  25.0    male  Third   7.0500         0
885  39.0  female  Third  29.1250         0
888   NaN  female  Third  23.4500         0
890  32.0    male  Third   7.7500         0

[491 rows x 5 columns]

In [53]:
# 여러 열을 기준으로 그룹화 
grouped_two = df.groupby(["class", "sex"])
grouped_two
grouped.std(numeric_only=True)

              age       fare  survived
class
First   14.802856  78.380373  0.484026
Second  14.001077  13.417399  0.500623
Third   12.495398  11.778142  0.428949

In [ ]:
for key, group in grouped_two: 
    print(key)
    print(group.head(2))
    print()

              age       fare  survived
class
First   14.802856  78.380373  0.484026
Second  14.001077  13.417399  0.500623
Third   12.495398  11.778142  0.428949

In [54]:
grouped_two.get_group(('Second', 'female'))

      age     sex   class     fare  survived
9    14.0  female  Second  30.0708         1
15   55.0  female  Second  16.0000         1
41   27.0  female  Second  21.0000         0
43    3.0  female  Second  41.5792         1
53   29.0  female  Second  26.0000         1
..    ...     ...     ...      ...       ...
854  44.0  female  Second  26.0000         0
865  42.0  female  Second  13.0000         1
866  27.0  female  Second  13.8583         1
874  28.0  female  Second  24.0000         1
880  25.0  female  Second  26.0000         1

[76 rows x 5 columns]

In [55]:
#df.groupby("class")
grouped["fare"].std()

class
First     78.380373
Second    13.417399
Third     11.778142
Name: fare, dtype: float64

In [56]:
grouped_two.mean(numeric_only=True)

                     age        fare  survived
class  sex
First  female  34.611765  106.125798  0.968085
       male    41.281386   67.226127  0.368852
Second female  28.722973   21.970121  0.921053
       male    30.740707   19.741782  0.157407
Third  female  21.750000   16.118810  0.500000
       male    26.507589   12.661633  0.135447

In [31]:
df.groupby("class")[["age","survived"]].std()

              age  survived
class
First   14.802856  0.484026
Second  14.001077  0.500623
Third   12.495398  0.428949

In [40]:
#group객체.aggregate(매핑함수) #집계함수
#group객체 agg(매핑함수)

df.groupby("class").agg("min",numeric_only=True)
#df.groupby("class").mean()
#df.groupby("class")[["fare","survived"].aggregate("min")]

         age  fare  survived
class
First   0.92   0.0         0
Second  0.67   0.0         0
Third   0.42   0.0         0

In [57]:
grouped = df.groupby(["class"])
grouped.std(numeric_only=True)

              age       fare  survived
class
First   14.802856  78.380373  0.484026
Second  14.001077  13.417399  0.500623
Third   12.495398  11.778142  0.428949

In [58]:
df.groupby("class").std(numeric_only=True)

              age       fare  survived
class
First   14.802856  78.380373  0.484026
Second  14.001077  13.417399  0.500623
Third   12.495398  11.778142  0.428949

In [59]:
df.groupby(["class"], as_index=False).std(numeric_only=True)

    class        age       fare  survived
0   First  14.802856  78.380373  0.484026
1  Second  14.001077  13.417399  0.500623
2   Third  12.495398  11.778142  0.428949

In [60]:
# grouped = df.groupby("class")
grouped["fare"].std()

class
First     78.380373
Second    13.417399
Third     11.778142
Name: fare, dtype: float64

In [61]:
imsi = df.groupby("class")["fare"].sum()
imsi["Second"].round(2)
df.groupby("class")[["age", "survived"]].std()

              age  survived
class
First   14.802856  0.484026
Second  14.001077  0.500623
Third   12.495398  0.428949

In [62]:
# group객체.aggregate(매핑함수)
# group객체.agg(매핑함수)

df.groupby("class").aggregate("mean", numeric_only=True)
# df.groupby("class").mean()
df.groupby("class")[["fare", "survived"]].aggregate("mean")
df.groupby("class")[["fare", "survived"]].agg("mean")

             fare  survived
class
First   84.154687  0.629630
Second  20.662183  0.472826
Third   13.675550  0.242363

In [37]:
df.groupby("class").agg(["min","max"])

         age           sex       fare           survived
         min   max     min   max  min       max      min max
class
First   0.92  80.0  female  male  0.0  512.3292        0   1
Second  0.67  70.0  female  male  0.0   73.5000        0   1
Third   0.42  74.0  female  male  0.0   69.5500        0   1

In [44]:
def min_max(x):
    return x.max() - x.min()
df.groupby("class")[["age","fare"]].agg(min_max)

          age      fare
class
First   79.08  512.3292
Second  69.33   73.5000
Third   73.58   69.5500