In [5]:
import pandas as pd
import numpy as np
df=pd.read_csv("./data/auto-mpg.csv",header=None)
df.columns = ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model year', 'origin', 'car name']
df.head(3)

    mpg  cylinders  displacement  ... model year  origin                   car name
0  18.0          8         307.0  ...         70       1  chevrolet chevelle malibu
1  15.0          8         350.0  ...         70       1          buick skylark 320
2  18.0          8         318.0  ...         70       1         plymouth satellite

[3 rows x 9 columns]

In [6]:
df["horsepower"]=df["horsepower"].replace("?",np.nan)
df=df.dropna(subset=["horsepower"])
df["horsepower"]=df["horsepower"].astype("float")
df.info

<bound method DataFrame.info of       mpg  cylinders  ...  origin                   car name
0    18.0          8  ...       1  chevrolet chevelle malibu
1    15.0          8  ...       1          buick skylark 320
2    18.0          8  ...       1         plymouth satellite
3    16.0          8  ...       1              amc rebel sst
4    17.0          8  ...       1                ford torino
..    ...        ...  ...     ...                        ...
393  27.0          4  ...       1            ford mustang gl
394  44.0          4  ...       2                  vw pickup
395  32.0          4  ...       1              dodge rampage
396  28.0          4  ...       1                ford ranger
397  31.0          4  ...       1                 chevy s-10

[392 rows x 9 columns]>

In [7]:
df["horsepower"].describe()
count,bin_dividers=np.histogram(df["horsepower"],bins=3)
print(count)
print(bin_dividers)

[257 103  32]
[ 46.         107.33333333 168.66666667 230.        ]

In [8]:
bin_names=["저출력","보통출력","고출력"]
df["hp_bin"]=pd.cut(
    x=df["horsepower"],
    bins=bin_dividers,
    labels=bin_names,
    include_lowest=True
)
df["hp_bin"]

0      보통출력
1      보통출력
2      보통출력
3      보통출력
4      보통출력
       ...
393     저출력
394     저출력
395     저출력
396     저출력
397     저출력
Name: hp_bin, Length: 392, dtype: category
Categories (3, str): ['저출력' < '보통출력' < '고출력']

In [9]:
#더미변수 #원확인코딩(?) ->True /False 해주는것
df["hp_bin"].value_counts()
pd.get_dummies(df["hp_bin"])

       저출력   보통출력    고출력
0    False   True  False
1    False   True  False
2    False   True  False
3    False   True  False
4    False   True  False
..     ...    ...    ...
393   True  False  False
394   True  False  False
395   True  False  False
396   True  False  False
397   True  False  False

[392 rows x 3 columns]

In [10]:
pd.get_dummies(df["hp_bin"],dtype=float)

     저출력  보통출력  고출력
0    0.0   1.0  0.0
1    0.0   1.0  0.0
2    0.0   1.0  0.0
3    0.0   1.0  0.0
4    0.0   1.0  0.0
..   ...   ...  ...
393  1.0   0.0  0.0
394  1.0   0.0  0.0
395  1.0   0.0  0.0
396  1.0   0.0  0.0
397  1.0   0.0  0.0

[392 rows x 3 columns]

In [11]:
pd.get_dummies(df["hp_bin"],dtype=float,drop_first=True)
#아니어도 알수있는 자료는 하나삭제해도됨
#ex)남여중 하나만해도 알수있음
#다중공성선회피..(?)

     보통출력  고출력
0     1.0  0.0
1     1.0  0.0
2     1.0  0.0
3     1.0  0.0
4     1.0  0.0
..    ...  ...
393   0.0  0.0
394   0.0  0.0
395   0.0  0.0
396   0.0  0.0
397   0.0  0.0

[392 rows x 2 columns]

In [ ]:
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

label_encoder=LabelEncoder()
#매핑시켜주는것 

onehot_encoder = OneHotEncoder()
onehot_labeled= label_encoder.fit_transform(df["hp_bin"].head(15))
#fit_transform 학습시킨데이터 
print(type(onehot_labeled))
print(onehot_labeled)
print(onehot_labeled.ndim)

<class 'numpy.ndarray'>
[1 1 1 1 1 0 0 0 0 0 0 1 1 0 2]
1

In [20]:
onegot_reshaped=onehot_labeled.reshape(len(onehot_labeled),1)
onehot_fifted=onehot_encoder.fit_transform(onegot_reshaped)
print(onehot_fifted)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 15 stored elements and shape (15, 3)>
  Coords	Values
  (0, 1)	1.0
  (1, 1)	1.0
  (2, 1)	1.0
  (3, 1)	1.0
  (4, 1)	1.0
  (5, 0)	1.0
  (6, 0)	1.0
  (7, 0)	1.0
  (8, 0)	1.0
  (9, 0)	1.0
  (10, 0)	1.0
  (11, 1)	1.0
  (12, 1)	1.0
  (13, 0)	1.0
  (14, 2)	1.0