In [ ]:
import pandas as pd
import seaborn as sns

titanic=sns.load_dataset("titanic")
df=titanic.loc[0:9,["age","fare"]]    #loc 행이름과 열이름 ,기준으로 행,

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
7   2.0  21.0750
8  27.0  11.1333
9  14.0  30.0708

In [ ]:
#불린 인덱싱
df["age"] <20  #비교연산자 결과값은 트루 펄스

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8    False
9     True
Name: age, dtype: bool

In [ ]:
#필터링 (아주중요!)
cond= df["age"] <20 
df[cond]
df.loc[cond]
#둘다가능

    age     fare
7   2.0  21.0750
9  14.0  30.0708

In [ ]:
cond= df["age"] <20 
df[~cond] #물결표시일시 False인거 보여줌

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
8  27.0  11.1333

In [9]:
#나이가 10대인 승객
#cond=df[10<=age<20]
(df["age"]>=10) & (df["age"]<20)

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9     True
Name: age, dtype: bool

In [11]:
cond=(df["age"]>=10) & (df["age"]<20)
df[cond]

    age     fare
9  14.0  30.0708

In [13]:
#titanic.age
cond= (titanic["age"] >= 10) & (titanic.age <20)
titanic[cond]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
22,1,3,female,15.0,0,0,8.0292,Q,Third,child,False,NaN,Queenstown,yes,True
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False
38,0,3,female,18.0,2,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
853,1,1,female,16.0,0,1,39.4000,S,First,woman,False,D,Southampton,yes,False
855,1,3,female,18.0,0,1,9.3500,S,Third,woman,False,NaN,Southampton,yes,False
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True
877,0,3,male,19.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True

In [18]:
#나이가 10세미만이고 여성인 승객
#titanic.head()
(titanic["age"] > 10) & (titanic["sex"] == "female")

titanic[(titanic["age"] > 10) & (titanic["sex"] == "female")]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True

In [19]:
#나이가 10세 미만 이고 또는 60세 이상인 승객 
cond=(titanic["age"] < 10) | (titanic["age"]>=60) #합집합 두개는 동싱에충족x
titanic[cond]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
7,0,3,male,2.00,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
10,1,3,female,4.00,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
16,0,3,male,2.00,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
24,0,3,female,8.00,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
33,0,2,male,66.00,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
831,1,2,male,0.83,1,1,18.7500,S,Second,child,False,NaN,Southampton,yes,False
850,0,3,male,4.00,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False
851,0,3,male,74.00,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True
852,0,3,female,9.00,1,1,15.2458,C,Third,child,False,NaN,Cherbourg,no,False
869,1,3,male,4.00,1,1,11.1333,S,Third,child,False,NaN,Southampton,yes,False

In [21]:
titanic["fare"][cond]

7      21.0750
10     16.7000
16     29.1250
24     21.0750
33     10.5000
        ...
831    18.7500
850    31.2750
851     7.7750
852    15.2458
869    11.1333
Name: fare, Length: 88, dtype: float64

In [22]:
df_under10 = titanic.loc[cond,["age","sex","alone"]]
df_under10

       age     sex  alone
7     2.00    male  False
10    4.00  female  False
16    2.00    male  False
24    8.00  female  False
33   66.00    male   True
..     ...     ...    ...
831   0.83    male  False
850   4.00    male  False
851  74.00    male   True
852   9.00  female  False
869   4.00    male  False

[88 rows x 3 columns]

In [23]:
titanic[["age","sex","alone"]][cond]

       age     sex  alone
7     2.00    male  False
10    4.00  female  False
16    2.00    male  False
24    8.00  female  False
33   66.00    male   True
..     ...     ...    ...
831   0.83    male  False
850   4.00    male  False
851  74.00    male   True
852   9.00  female  False
869   4.00    male  False

[88 rows x 3 columns]

In [31]:
df["age_under_20"] = df["age"]<20
df

    age  parch  age_under_20
0  22.0      0         False
1  38.0      0         False
2  26.0      0         False
3  35.0      0         False
4  35.0      0         False
5   NaN      0         False
6  54.0      0         False
7   2.0      1          True
8  27.0      2         False
9  14.0      0          True

In [28]:
#query() 메서드활용
#DataFream객체.qurey(조건문자열)

df = titanic.loc[:9, ["age", "parch"]]
#df= titanic.loc[:9,["age","pare"]]
df

    age  parch
0  22.0      0
1  38.0      0
2  26.0      0
3  35.0      0
4  35.0      0
5   NaN      0
6  54.0      0
7   2.0      1
8  27.0      2
9  14.0      0

In [30]:
titanic.query("age >= 20 and fare < 15")

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [33]:
#나이가 20세 이상 
titanic.query("age>=20 or fare<15")

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [37]:
#isin()메서드 활용 
#DataFreame객체.isin(추출값의리스트)
pd.set_option("display.max_columns",10)
titanic

,survived,pclass,sex,age,sibsp,...,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,...,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,...,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,...,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,...,False,C,Southampton,yes,False
4,0,3,male,35.0,0,...,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,...,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,...,False,B,Southampton,yes,True
888,0,3,female,NaN,1,...,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,...,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,...,True,NaN,Queenstown,no,True

In [46]:
mask1=titanic["embark_town"]=="Southampton"
marsk2=titanic["embark_town"]=="Queenstown"
df_boolsen=titanic[mask1|marsk2]
df_boolsen

,survived,pclass,sex,age,sibsp,...,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,...,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,...,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,...,False,C,Southampton,yes,False
4,0,3,male,35.0,0,...,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,...,True,NaN,Queenstown,no,True
...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,female,39.0,0,...,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,...,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,...,False,B,Southampton,yes,True
888,0,3,female,NaN,1,...,False,NaN,Southampton,no,False
890,0,3,male,32.0,0,...,True,NaN,Queenstown,no,True

In [ ]:
mask3 = titanic["embark_town"].isin(["Southampton", "Queenstown"])
titanic[mask3]

,survived,pclass,sex,age,sibsp,...,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,...,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,...,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,...,False,C,Southampton,yes,False
4,0,3,male,35.0,0,...,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,...,True,NaN,Queenstown,no,True
...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,female,39.0,0,...,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,...,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,...,False,B,Southampton,yes,True
888,0,3,female,NaN,1,...,False,NaN,Southampton,no,False
890,0,3,male,32.0,0,...,True,NaN,Queenstown,no,True

In [51]:
import pandas as pd
pruit_name=pd.Series(
    ["Apple","Banana","Cherry"],dtype="string"
)
pruit_name.dtype

In [58]:
import pandas as pd
import numpy as np


ser=pd.Series(
    ["Apple_사과","Banana_바나나","Cherry_체리",np.nan],
    index=["First ","Second ","Third","fourth"]

)
print(ser)
print()

ser2=pd.Series(
    ["Apple_사과","Banana_바나나","Cherry_체리",np.nan],
    index=["First ","Second ","Third","fourth"],
    dtype="string"
)
print(ser2)

First        Apple_사과
Second     Banana_바나나
Third       Cherry_체리
fourth            NaN
dtype: str

First        Apple_사과
Second     Banana_바나나
Third       Cherry_체리
fourth           <NA>
dtype: string

In [60]:
ser.str.upper()

First        APPLE_사과
Second     BANANA_바나나
Third       CHERRY_체리
fourth            NaN
dtype: str

In [62]:
ser.str.len()

First       8.0
Second     10.0
Third       9.0
fourth      NaN
dtype: float64

In [64]:
ser.str.split("_")

First        [Apple, 사과]
Second     [Banana, 바나나]
Third       [Cherry, 체리]
fourth               NaN
dtype: object

In [67]:
ser.str.split("_",expand=True)

              0    1
First     Apple   사과
Second   Banana  바나나
Third    Cherry   체리
fourth      NaN  NaN

In [68]:
ser.str.split("_").str.get(1)

First       사과
Second     바나나
Third       체리
fourth     NaN
dtype: object

In [70]:
idx=ser.index

In [71]:
idx.str.strip()

Index(['First', 'Second', 'Third', 'fourth'], dtype='str')

In [73]:
idx.str.rstrip()
idx.str.lstrip()

Index(['First ', 'Second ', 'Third', 'fourth'], dtype='str')

In [75]:
ser.str.replace("_",":",regex=False)

First        Apple:사과
Second     Banana:바나나
Third       Cherry:체리
fourth            NaN
dtype: str

In [ ]:
ser.str.replace("[^a-zA-z0-9]","",regex=True) #a-zA-z0-9 , a-zA-z\s 영어소문자 영어대문자 숫자

First       Apple_
Second     Banana_
Third      Cherry_
fourth         NaN
dtype: str

In [78]:
ser.str.replace("[a-zA-z0-9]","",regex=True) #a-zA-z0-9 , a-zA-z\s 영어소문자 영어대문자 숫자

First       사과
Second     바나나
Third       체리
fourth     NaN
dtype: str

In [ ]:
ser.str[0]

First        A
Second       B
Third        C
fourth     NaN
dtype: str

In [ ]:
ser.str[0:4] #슬라이싱

First      Appl
Second     Bana
Third      Cher
fourth      NaN
dtype: str

In [82]:
ser.str.contains("A",na=False) #A가포함되어있는지 확인

First       True
Second     False
Third      False
fourth     False
dtype: bool

In [ ]:
ser.str.contains(r"[A|B][a-z]+") #r은 레직스 정규표현식이란뜻

First       True
Second      True
Third      False
fourth     False
dtype: bool

In [86]:
ser.str.fullmatch(r"[A|B|C][a-z]+_[가-힣]+")

First       True
Second      True
Third       True
fourth     False
dtype: bool