In [1]:
import pandas as pd
df=pd.read_csv("./data/stock-data.csv")
df.head()
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    20 non-null     str
 1   Close   20 non-null     int64
 2   Start   20 non-null     int64
 3   High    20 non-null     int64
 4   Low     20 non-null     int64
 5   Volume  20 non-null     int64
dtypes: int64(5), str(1)
memory usage: 1.1 KB

Date      0
Close     0
Start     0
High      0
Low       0
Volume    0
dtype: int64

In [2]:
#문자열을 timestamp로 변환
df["Date"]
df["new_date"]=pd.to_datetime(df["Date"])
df.head()
df.info()

df=df.set_index("new_date")
df= df.drop("Date",axis=1)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      20 non-null     str
 1   Close     20 non-null     int64
 2   Start     20 non-null     int64
 3   High      20 non-null     int64
 4   Low       20 non-null     int64
 5   Volume    20 non-null     int64
 6   new_date  20 non-null     datetime64[us]
dtypes: datetime64[us](1), int64(5), str(1)
memory usage: 1.2 KB
<class 'pandas.DataFrame'>
DatetimeIndex: 20 entries, 2018-07-02 to 2018-06-01
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Close   20 non-null     int64
 1   Start   20 non-null     int64
 2   High    20 non-null     int64
 3   Low     20 non-null     int64
 4   Volume  20 non-null     int64
dtypes: int64(5)
memory usage: 960.0 bytes

In [3]:
pd.DatetimeIndex([
    "2022-12-25" , "2023/01/25"
])

DatetimeIndex(['2022-12-25', '2023-01-25'], dtype='datetime64[us]', freq=None)

In [5]:
pd.Timestamp("2023-12-25")
pd.Timestamp("2023/12/25")

Timestamp('2023-12-25 00:00:00')

In [6]:
pd.to_datetime("2025/12/25")

Timestamp('2025-12-25 00:00:00')

In [13]:
pd.to_datetime("2025년 12월 25일",format="%Y년 %m월 %d일")
pd.to_datetime("2025:12:25", format="%Y:%m:%d")

Timestamp('2025-12-25 00:00:00')

In [12]:
pd.to_datetime("12-12-2026 23:59:59", format="%d-%m-%Y %H:%M:%S")

Timestamp('2026-12-12 23:59:59')

In [15]:
#timestamp를 이용해서 period로 변환
dates=["2019-01-01","2020-03-01","2021-06-01"]
ts_dates=pd.to_datetime(dates)
ts_dates.to_period(freq="D")

PeriodIndex(['2019-01-01', '2020-03-01', '2021-06-01'], dtype='period[D]')

In [18]:
tr_month=ts_dates.to_period(freq="M")
tr_month
tr_Year=ts_dates.to_period(freq="Y")
tr_Year

PeriodIndex(['2019', '2020', '2021'], dtype='period[Y-DEC]')

In [ ]:
#시계열 데이터 만들기
ts_ms=pd.date_range(
    start="2024-01-01",
    end=None,
    periods=6,
    freq="MS", #먼스스타트
    tz="Asia/Seoul"
)
ts_ms

DatetimeIndex(['2024-01-01 00:00:00+09:00', '2024-02-01 00:00:00+09:00',
               '2024-03-01 00:00:00+09:00', '2024-04-01 00:00:00+09:00',
               '2024-05-01 00:00:00+09:00', '2024-06-01 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='MS')

In [24]:
ts_me=pd.date_range(
    start="2024-01-01",
    end=None,
    periods=6,
    freq="ME", #먼스앤드 
    tz="Asia/Seoul"
)
ts_me

DatetimeIndex(['2024-01-31 00:00:00+09:00', '2024-02-29 00:00:00+09:00',
               '2024-03-31 00:00:00+09:00', '2024-04-30 00:00:00+09:00',
               '2024-05-31 00:00:00+09:00', '2024-06-30 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='ME')

In [27]:
ts_3m=pd.date_range(
    "2024-01-01",
    periods=6,
    freq="3MS",
    tz="Asia/Seoul"
)
ts_3m

DatetimeIndex(['2024-01-01 00:00:00+09:00', '2024-04-01 00:00:00+09:00',
               '2024-07-01 00:00:00+09:00', '2024-10-01 00:00:00+09:00',
               '2025-01-01 00:00:00+09:00', '2025-04-01 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='3MS')

In [36]:
#시계열데이터활용 
df=pd.read_csv("./data/stock-data.csv")
df.head()

         Date  Close  Start   High    Low  Volume
0  2018-07-02  10100  10850  10900  10000  137977
1  2018-06-29  10700  10550  10900   9990  170253
2  2018-06-28  10400  10900  10950  10150  155769
3  2018-06-27  10900  10800  11050  10500  133548
4  2018-06-26  10800  10900  11000  10700   63039

In [37]:
df["new_Date"]=pd.to_datetime(df["Date"])
df.head()

         Date  Close  Start   High    Low  Volume   new_Date
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26

In [42]:
df["new_Date"].dt.year
df["month"]=df["new_Date"].dt.month
df["day"]=df["new_Date"].dt.day
df.head()

         Date  Close  Start   High    Low  Volume   new_Date  month  day
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02      7    2
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29      6   29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28      6   28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27      6   27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26      6   26

In [46]:
df["DATE_Y"]=df["new_Date"].dt.to_period(freq="Y")
df["DATE_M"]=df["new_Date"].dt.to_period(freq="M")
df["DATE_D"]=df["new_Date"].dt.to_period(freq="D")
df.head()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      20 non-null     str
 1   Close     20 non-null     int64
 2   Start     20 non-null     int64
 3   High      20 non-null     int64
 4   Low       20 non-null     int64
 5   Volume    20 non-null     int64
 6   new_Date  20 non-null     datetime64[us]
 7   month     20 non-null     int32
 8   day       20 non-null     int32
 9   DATE_Y    20 non-null     period[Y-DEC]
 10  DATE_M    20 non-null     period[M]
 11  DATE_D    20 non-null     period[D]
dtypes: datetime64[us](1), int32(2), int64(5), period[D](1), period[M](1), period[Y-DEC](1), str(1)
memory usage: 1.8 KB

In [49]:
mask=df["DATE_M"].astype(str).str.fullmatch("2018-06")
df_june =df[mask]
df_june

,Date,Close,Start,High,Low,Volume,new_Date,month,day,DATE_Y,DATE_M,DATE_D
1,2018-06-29,10700,10550,10900,9990,170253,2018-06-29,6,29,2018,2018-06,2018-06-29
2,2018-06-28,10400,10900,10950,10150,155769,2018-06-28,6,28,2018,2018-06,2018-06-28
3,2018-06-27,10900,10800,11050,10500,133548,2018-06-27,6,27,2018,2018-06,2018-06-27
4,2018-06-26,10800,10900,11000,10700,63039,2018-06-26,6,26,2018,2018-06,2018-06-26
5,2018-06-25,11150,11400,11450,11000,55519,2018-06-25,6,25,2018,2018-06,2018-06-25
6,2018-06-22,11300,11250,11450,10750,134805,2018-06-22,6,22,2018,2018-06,2018-06-22
7,2018-06-21,11200,11350,11750,11200,133002,2018-06-21,6,21,2018,2018-06,2018-06-21
8,2018-06-20,11550,11200,11600,10900,308596,2018-06-20,6,20,2018,2018-06,2018-06-20
9,2018-06-19,11300,11850,11950,11300,180656,2018-06-19,6,19,2018,2018-06,2018-06-19
10,2018-06-18,12000,13400,13400,12000,309787,2018-06-18,6,18,2018,2018-06,2018-06-18
11,2018-06-15,13400,13600,13600,12900,201376,2018-06-15,6,15,2018,2018-06,2018-06-15
12,2018-06-14,13450,13200,13700,13150,347451,2018-06-14,6,14,2018,2018-06,2018-06-14
13,2018-06-12,13200,12200,13300,12050,558148,2018-06-12,6,12,2018,2018-06,2018-06-12
14,2018-06-11,11950,12000,12250,11950,62293,2018-06-11,6,11,2018,2018-06,2018-06-11
15,2018-06-08,11950,11950,12200,11800,59258,2018-06-08,6,8,2018,2018-06,2018-06-08
16,2018-06-07,11950,12200,12300,11900,49088,2018-06-07,6,7,2018,2018-06,2018-06-07
17,2018-06-05,12150,11800,12250,11800,42485,2018-06-05,6,5,2018,2018-06,2018-06-05
18,2018-06-04,11900,11900,12200,11700,25171,2018-06-04,6,4,2018,2018-06,2018-06-04
19,2018-06-01,11900,11800,12100,11750,32062,2018-06-01,6,1,2018,2018-06,2018-06-01

In [ ]:
#시간인덱스활용
df=pd.read_csv("./data/stock-data.csv")
df.head()
df["new_Date"]=pd.to_datetime(df["Date"])
df.head()
df=df.set_index("new_Date")
df.head()
df=df.sort_index(ascending=True)
df.head()
#df.sort_values()

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-01  2018-06-01  11900  11800  12100  11750   32062
2018-06-04  2018-06-04  11900  11900  12200  11700   25171
2018-06-05  2018-06-05  12150  11800  12250  11800   42485
2018-06-07  2018-06-07  11950  12200  12300  11900   49088
2018-06-08  2018-06-08  11950  11950  12200  11800   59258

In [55]:
df.loc["2018-06-27"]
df.loc["2018-06-27":"2018-07-25"]

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-27  2018-06-27  10900  10800  11050  10500  133548
2018-06-28  2018-06-28  10400  10900  10950  10150  155769
2018-06-29  2018-06-29  10700  10550  10900   9990  170253
2018-07-02  2018-07-02  10100  10850  10900  10000  137977

In [56]:
cond=df.index<"2018-06-05"
cond

array([ True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [57]:
df[cond]

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-01  2018-06-01  11900  11800  12100  11750   32062
2018-06-04  2018-06-04  11900  11900  12200  11700   25171

In [59]:
pd.Timestamp("2018-06-27")
pd.Timestamp(2018,6,27)

Timestamp('2018-06-27 00:00:00')

In [ ]:
df.loc[pd.Timestamp(2018,6,27):pd.Timestamp(2018,7,2)]

Timestamp('2018-06-07 20:30:00')

In [65]:
df.loc[
    pd.Timestamp(2018,6,7,20,30,0):pd.Timestamp(2018,7,2,23,59,59)
]
#pd.Timestamp(2018,6,7,20,30,0)

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-08  2018-06-08  11950  11950  12200  11800   59258
2018-06-11  2018-06-11  11950  12000  12250  11950   62293
2018-06-12  2018-06-12  13200  12200  13300  12050  558148
2018-06-14  2018-06-14  13450  13200  13700  13150  347451
2018-06-15  2018-06-15  13400  13600  13600  12900  201376
2018-06-18  2018-06-18  12000  13400  13400  12000  309787
2018-06-19  2018-06-19  11300  11850  11950  11300  180656
2018-06-20  2018-06-20  11550  11200  11600  10900  308596
2018-06-21  2018-06-21  11200  11350  11750  11200  133002
2018-06-22  2018-06-22  11300  11250  11450  10750  134805
2018-06-25  2018-06-25  11150  11400  11450  11000   55519
2018-06-26  2018-06-26  10800  10900  11000  10700   63039
2018-06-27  2018-06-27  10900  10800  11050  10500  133548
2018-06-28  2018-06-28  10400  10900  10950  10150  155769
2018-06-29  2018-06-29  10700  10550  10900   9990  170253
2018-07-02  2018-07-02  10100  10850  10900  10000  137977