In [1]:
#2가지이상의 시리즈를 가지고있을때 데이터프레임
import pandas as pd

In [2]:
#데이터프레임 = pandas.DataFrame(데이터)
#시리즈 =pandas.Series(데이터)

In [3]:
import pandas as pd

dict_data={
    "c0":[1,2,3],
    "c1":[4,5,6],
    "c2":[7,8,9],
    "c3":[10,11,12],
    "c4":[13,14,15]
}

df = pd.DataFrame(dict_data)
print(type(df))
print(df)

<class 'pandas.DataFrame'>
   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [4]:
#행 인덱스 /열 이름 설정
import pandas as pd
data=[
    [15,"남","덕영중"],
    [17,"여","수리중"]
]

df=pd.DataFrame(data, index=["준서","예은"],columns=["나이","성별","학교"])
print(df)
print(df.index)
print(df.columns)
#2행3열

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중
Index(['준서', '예은'], dtype='str')
Index(['나이', '성별', '학교'], dtype='str')

In [5]:
df.index = ["학생1","학생2"]
df

     나이 성별   학교
학생1  15  남  덕영중
학생2  17  여  수리중

In [6]:
df.columns =["연령","남녀","소속"]
df

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [7]:
import pandas as pd
data=[
    [15,"남","덕영중"],
    [17,"여","수리중"]
]
df=pd.DataFrame(data, index=["준서","예은"],columns=["나이","성별","학교"])
df= df.rename(columns={"나이":"연령","성별":"남녀","학교":"소속"})
df

    연령 남녀   소속
준서  15  남  덕영중
예은  17  여  수리중

In [8]:
df=df.rename(index={
    "준서":"학생1",
    "예은":"학생2"
})
df

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [9]:
# #행/열 삭제
# 행삭제:DataFrame객체.drop(행인덱스 또는 배열,axis=0또는 axis="index") #기본은 0
# 열삭제:DataFrame객체.drop(열이름 똔느 배열 , axis=1 또는 axis="colums") 
# 지울때 엑시스로 지우려면 가로가0 집계함수할때는 세로가 0 
#헷갈리니까 엑시스 index와 colums쓰자

In [10]:
# 행삭제:DataFrame객체.drop(행인덱스 또는 배열,axis=0또는 axis="index") #기본은 0
# 열삭제:DataFrame객체.drop(열이름 똔느 배열 , axis=1 또는 axis="colums") 
import pandas as pd

exam_data = {
    "수학":[90,80,70],
    "영어":[98,89,95],
    "음악":[85,95,100],
    "체육":[100,90,90]
}
pd.DataFrame(exam_data,index=["서준","우현","인한"])

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인한  70  95  100   90

In [11]:
import pandas as pd

exam_data = {
    "수학":[90,80,70],
    "영어":[98,89,95],
    "음악":[85,95,100],
    "체육":[100,90,90]
}
df=pd.DataFrame(exam_data,index=["서준","우현","인한"])

df2 = df.copy()
df2= df2.drop("우현",axis=0) #axis=0 기본값이라 안써도 자동으로 우현지워짐
df2

    수학  영어   음악   체육
서준  90  98   85  100
인한  70  95  100   90

In [12]:
import pandas as pd

exam_data = {
    "수학":[90,80,70],
    "영어":[98,89,95],
    "음악":[85,95,100],
    "체육":[100,90,90]
}
df=pd.DataFrame(exam_data,index=["서준","우현","인한"])

df3 = df.copy()
df3 = df3.drop(["우현","인한"],axis=0)
df3

    수학  영어  음악   체육
서준  90  98  85  100

In [13]:
df5 = df.copy()
df5.drop(index=["우현"])

    수학  영어   음악   체육
서준  90  98   85  100
인한  70  95  100   90

In [14]:
#열삭제
df2=df.copy()
df2.drop("수학",axis=1)

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인한  95  100   90

In [15]:
df3=df.copy()
df3 = df3.drop(["영어","음악"],axis=1)
df3

    수학   체육
서준  90  100
우현  80   90
인한  70   90

In [16]:
df4 = df.copy()
df4= df4.drop(["영어","음악"],axis="columns")
df4

    수학   체육
서준  90  100
우현  80   90
인한  70   90

In [17]:
df5 = df.copy()
df5= df5.drop(columns=["수학"])
df5

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인한  95  100   90

In [18]:
#행선택 
df.loc["서준"]
type(df.loc["서준"])

pandas.Series

In [19]:
label1=df.loc["서준"] #인덱스명
position1=df.iloc[0] #인덱스번호
print(label1)
print("========")
print(position1)

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64
========
수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

In [20]:
print(df.loc[["서준","우현"]])
print()
print(df.iloc[[0,1]])
type((df.loc[["서준","우현"]]))

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

pandas.DataFrame

In [21]:
#행선택
print(df.loc["서준": "우현"])
print("=====")
print(df.iloc[0:1])

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90
=====
    수학  영어  음악   체육
서준  90  98  85  100

In [22]:
#열선택
df["수학"]
type(df["수학"])

pandas.Series

In [23]:
df.영어
#만약 명칭사이에 공백이있다면 df["수   학"]

서준    98
우현    89
인한    95
Name: 영어, dtype: int64

In [24]:
df[["영어","체육"]]

    영어   체육
서준  98  100
우현  89   90
인한  95   90

In [25]:
print(df["영어"])
print("===")
print(df[["영어"]])

서준    98
우현    89
인한    95
Name: 영어, dtype: int64
===
    영어
서준  98
우현  89
인한  95

In [26]:
print(type(df["영어"]))
print("===")
print(type(df[["영어"]])) 
#라벨코딩 원학코딩(?)할때 씀 데이터프레임형태로넣어야하기때문에 둘은 엄연히 다름

<class 'pandas.Series'>
===
<class 'pandas.DataFrame'>

In [27]:
#원소 선택 
exam_data = {
    "이름":["서준","우현","인아"],
    "수학":[90,80,70],
    "영어":[98,89,95],
    "음악":[85,95,100],
    "체육":[100,90,90]
}
df=pd.DataFrame(exam_data)

In [28]:
print(df.loc[0:2])
print("==")
print(df.iloc[0:2])

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
==
   이름  수학  영어  음악   체육
0  서준  90  98  85  100
1  우현  80  89  95   90

In [29]:
exam_data = {
    "이름":["서준","우현","인아"],
    "수학":[90,80,70],
    "영어":[98,89,95],
    "음악":[85,95,100],
    "체육":[100,90,90]
}
df=pd.DataFrame(exam_data)
df=df.set_index("이름")
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [30]:
exam_data = {
    "이름":["서준","우현","인아"],
    "수학":[90,80,70],
    "영어":[98,89,95],
    "음악":[85,95,100],
    "체육":[100,90,90]
}
df=pd.DataFrame(exam_data)
df = df.set_index("이름")
df.loc["서준"]
df.loc["서준","음악"]
df.iloc[0,2]

np.int64(85)

In [31]:
exam_data = {
    "이름":["서준","우현","인아"],
    "수학":[90,80,70],
    "영어":[98,89,95],
    "음악":[85,95,100],
    "체육":[100,90,90]
}
df=pd.DataFrame(exam_data)
df = df.set_index("이름")
df.loc["서준"]
print(df.loc["서준",['음악','체육']])
print(df.iloc[0,[2,3]])

음악     85
체육    100
Name: 서준, dtype: int64
음악     85
체육    100
Name: 서준, dtype: int64

In [32]:
df
print(df.loc["서준","음악":"체육"])
print()
print(df.iloc[0,2:]) #처음,끝,넘어가는범위
print(df.iloc[0,2:]) #처음,끝,넘어가는범위
#[0,2:] 0번 행인 서준이의 2번부터 4번째 열을 다달라

음악     85
체육    100
Name: 서준, dtype: int64

음악     85
체육    100
Name: 서준, dtype: int64
음악     85
체육    100
Name: 서준, dtype: int64

In [33]:
#열추가
#데이터프레임객체["열이름"] = 데이터값
import pandas as pd
exam_data = {
    "이름":["서준","우현","인아"],
    "수학":[90,80,70],
    "영어":[98,89,95],
    "음악":[85,95,100],
    "체육":[100,90,90]
}
df=pd.DataFrame(exam_data)
df["국어"] = 80
df
df["미술"]=[80,90,100]
df

   이름  수학  영어   음악   체육  국어   미술
0  서준  90  98   85  100  80   80
1  우현  80  89   95   90  80   90
2  인아  70  95  100   90  80  100

In [34]:
#행추가
#DataFrame객체.loc["행이름"] = 데이터값
import pandas as pd
exam_data = {
    "이름":["서준","우현","인아"],
    "수학":[90,80,70],
    "영어":[98,89,95],
    "음악":[85,95,100],
    "체육":[100,90,90]
}
df = pd.DataFrame(exam_data)
df.loc[3] =0
df.loc[4] = ["동규",90,80,70,60]
df.loc["행5"]=df.loc[1]
df

    이름  수학  영어   음악   체육
0   서준  90  98   85  100
1   우현  80  89   95   90
2   인아  70  95  100   90
3    0   0   0    0    0
4   동규  90  80   70   60
행5  우현  80  89   95   90

In [35]:
#원소값 변경
import pandas as pd

exam_data = {
    "이름":["서준","우현","인아"],
    "수학":[90,80,70],
    "영어":[98,89,95],
    "음악":[85,95,100],
    "체육":[100,90,90]
}

df=pd.DataFrame(exam_data)
df=df.set_index("이름")
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [36]:
df.iloc[0]
df.iloc[0,3]=80
df

    수학  영어   음악  체육
이름
서준  90  98   85  80
우현  80  89   95  90
인아  70  95  100  90

In [37]:
df.loc["서준"]["체육"] 
df.loc["서준","체육"]= 90 
df

    수학  영어   음악  체육
이름
서준  90  98   85  90
우현  80  89   95  90
인아  70  95  100  90

In [38]:
df.loc["서준",["음악","체육"]] = 50
df

    수학  영어   음악  체육
이름
서준  90  98   50  50
우현  80  89   95  90
인아  70  95  100  90

In [39]:
df.loc["서준",["음악","체육"]] =100,50
df

    수학  영어   음악  체육
이름
서준  90  98  100  50
우현  80  89   95  90
인아  70  95  100  90

In [40]:
# #행과 열의 위치 바꾸기
# DataFrame.객체.transpose()
# dataFrame.객체.T

In [41]:
import pandas as pd

exam_data = {
    "이름":["서준","우현","인아"],
    "수학":[90,80,70],
    "영어":[98,89,95],
    "음악":[85,95,100],
    "체육":[100,90,90]
}
df=pd.DataFrame(exam_data)
df = df.transpose()
df

      0   1    2
이름   서준  우현   인아
수학   90  80   70
영어   98  89   95
음악   85  95  100
체육  100  90   90

In [42]:
df=df.T
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90